global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "batch"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081 #도커 컨테이너에서 내 컴퓨터(로컬)를 의미
