spring.application.name=api
spring.profiles.active=prod

# JWT \uC124\uC815 
jwt.secret=${JWT_SECRET}

# TMDB API \uD1A0\uD070 (\uACF5\uD1B5)
custom.tmdb.access-token=${TMDB_ACCESS_TOKEN}

# Actuator endpoint \uBAA8\uB450 \uB178\uCD9C
management.endpoints.web.exposure.include=*
