# ----- API local, MySQL Docker -----
# 1. 로컬 MySQL 연결 설정 (localhost로 설정)
spring.datasource.url=jdbc:mysql://localhost:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=app
spring.datasource.password=app

# 2. H2 데이터베이스 (사용 안 함)
spring.h2.console.enabled=false

# 3. JPA 설정 (MySQL), create는 기존 테이블 삭제
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Redis 설정
# 도커로 띄운 Redis에 localhost:6379로 접속합니다.
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 5. SQL 초기화 설정 (schema.sql 자동 실행 방지, 항상 never)
spring.sql.init.mode=never