server.port=8081

spring.datasource.url=jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=app
spring.datasource.password=app

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# \u2705 Spring Batch \uBA54\uD0C0 \uD14C\uC774\uBE14 \uC790\uB3D9 \uC0DD\uC131
spring.batch.jdbc.initialize-schema=never

spring.batch.job.enabled=false

custom.tmdb.access-token=${TMDB_ACCESS_TOKEN}

# \u2705 Actuator endpoint \uB178\uCD9C
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# \u2705 Prometheus endpoint \uD65C\uC131\uD654 (\uC774\uAC8C \uBE60\uC838 \uC788\uC5C8\uC74C)
management.endpoint.prometheus.enabled=true

# \u2705 actuator \uAE30\uBCF8 \uACBD\uB85C
management.endpoints.web.base-path=/actuator

# \u2705 Spring Batch \uBA54\uD2B8\uB9AD
management.metrics.enable.spring.batch=true

