spring.application.name=batch
spring.profiles.active=docker

# \u2705 Actuator \uB178\uCD9C \uC124\uC815
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

