plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.sprint'
version = '0.0.1-SNAPSHOT'
description = 'batch'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-batch'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	// ✅ Batch 테스트는 Boot starter가 아니라 Spring Batch 테스트 모듈을 사용
	testImplementation 'org.springframework.batch:spring-batch-test'

	// ✅ MySql
	implementation 'com.mysql:mysql-connector-j'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// ✅ JPA, MySQL 관련 (이게 있어야 jakarta.persistence 에러가 사라집니다)
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// ✅  Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
}


tasks.named('test') {
	useJUnitPlatform()
}
